from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest


WIKI = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("wiki_build", WIKI / "build.py")
assert SPEC and SPEC.loader
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


def test_living_manuscript_contract_is_complete():
    report = MODULE.check()
    assert report["body_words"] >= 3500
    assert report["abstract_words"] >= 120
    assert report["citation_count"] >= 40
    assert report["bibliography_count"] >= 45


def test_split_excludes_wiki_banner_and_retains_paper_body():
    text = (WIKI / "Full-Manuscript.md").read_text(encoding="utf-8")
    abstract, body = MODULE.split_manuscript(text)
    assert "Living manuscript" not in body
    assert abstract.startswith("Magnetic-core models")
    assert body.startswith("# Introduction")
    assert "# Conclusion" in body


def test_unresolved_citation_is_rejected():
    assert MODULE.citation_keys("statement [@missing2026]") == {"missing2026"}
    available = MODULE.bibliography_keys(WIKI / "bibliography" / "references.bib")
    assert "missing2026" not in available


def test_snapshot_refuses_existing_output(tmp_path: Path):
    output = tmp_path / "already-exists"
    output.mkdir()
    with pytest.raises(MODULE.WikiError, match="already exists"):
        MODULE.snapshot(output)


@pytest.mark.parametrize(
    "text",
    [
        "token gh" + "p_ABCDEFGHIJKLMNOPQRSTUVWXYZ123456",
        "generated by Chat" + "GPT",
        "/" + "users/example/private/project",
        "Current Presen" + "tation note",
    ],
)
def test_public_disclosure_patterns_are_detected(text: str):
    assert any(pattern.search(text) for pattern in MODULE.BANNED_PUBLIC_PATTERNS.values())
