from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest


WIKI = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("wiki_build", WIKI / "build.py")
assert SPEC and SPEC.loader
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


def test_living_manuscript_contract_is_complete():
    report = MODULE.check()
    assert report["body_words"] >= 3500
    assert report["abstract_words"] >= 120
    assert report["citation_count"] >= 40
    assert report["bibliography_count"] >= 45


def test_split_retains_complete_paper_body():
    text = (WIKI / "Full-Manuscript.md").read_text(encoding="utf-8")
    abstract, body = MODULE.split_manuscript(text)
    assert abstract.startswith("Magnetic-core models")
    assert body.startswith("# Introduction")
    assert "# Conclusion" in body


def test_unresolved_citation_is_rejected():
    assert MODULE.citation_keys("statement [@missing2026]") == {"missing2026"}
    available = MODULE.bibliography_keys(WIKI / "bibliography" / "references.bib")
    assert "missing2026" not in available


def test_snapshot_refuses_existing_output(tmp_path: Path):
    output = tmp_path / "already-exists"
    output.mkdir()
    with pytest.raises(MODULE.WikiError, match="already exists"):
        MODULE.snapshot(output)


def test_scientific_job_registry_covers_declared_artifacts():
    evidence = json.loads(
        (WIKI / "evidence" / "results.json").read_text(encoding="utf-8")
    )
    assert len(evidence["scientific_jobs"]) == 13
    assert sum(job["artifacts"] for job in evidence["scientific_jobs"]) == 222
    assert evidence["campaign"]["result_artifact_count"] == 222
    assert evidence["sources"]["acquisition_record_set"]["record_count"] == 30


def test_comparator_explanation_is_source_bound():
    page = (WIKI / "Scientific-Job-Results.md").read_text(encoding="utf-8")
    assert "Why EIG did not beat the strong comparators" in page
    assert "Evidence-Sources.md#e4" in page
    assert "Evidence-Sources.md#e5" in page
    for source_id in range(1, 9):
        assert f'<a id="e{source_id}"></a>' in (
            WIKI / "Evidence-Sources.md"
        ).read_text(encoding="utf-8")


def test_new_reader_index_covers_public_pages_and_evidence_lookup():
    index = (WIKI / "Wiki-Index.md").read_text(encoding="utf-8")
    for page in MODULE.REQUIRED_PAGES - {"README.md", "_Sidebar.md", "Wiki-Index.md"}:
        assert f"]({page})" in index or f"]({page}#" in index
    assert "How to verify a number" in index
    for source_id in range(1, 9):
        assert f"Evidence-Sources.md#e{source_id}" in index


def test_acquisition_figure_is_bound_to_evidence_projection():
    evidence = WIKI / "evidence" / "results.json"
    manifest = json.loads(
        (WIKI / "assets" / "acquisition-diagnostics.json").read_text(
            encoding="utf-8"
        )
    )
    assert manifest["evidence_projection_sha256"] == MODULE.sha256(evidence)
    assert manifest["figure_sha256"] == MODULE.sha256(
        WIKI / "assets" / manifest["figure"]
    )
    assert manifest["evidence_sources"] == ["E4", "E5"]


@pytest.mark.parametrize(
    "text",
    [
        "token gh" + "p_ABCDEFGHIJKLMNOPQRSTUVWXYZ123456",
        "generated by "
        + "".join(chr(value) for value in (67, 104, 97, 116, 71, 80, 84)),
        "/" + "users/example/private/project",
        "Current Presen" + "tation note",
        "The current manuscript preser" + "ves the old layout",
        "a one-way mir" + "ror of the source",
        "This wiki is the liv" + "ing manuscript",
    ],
)
def test_public_disclosure_patterns_are_detected(text: str):
    assert any(pattern.search(text) for pattern in MODULE.BANNED_PUBLIC_PATTERNS.values())


def test_repository_landing_page_is_evidence_led():
    readme = (WIKI.parent / "README.md").read_text(encoding="utf-8")
    assert "## Main result" in readme
    assert "wiki/Evidence-Sources.md#e4" in readme
    assert "wiki/Evidence-Sources.md#e5" in readme
    assert "wiki/Evidence-Sources.md#e7" in readme
    assert "20260817T072230Z_401e3030fe13" in readme
    assert MODULE.sha256(WIKI.parent / "README.md") == MODULE.check()[
        "repository_readme_sha256"
    ]
