from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path

import pytest


WIKI = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("wiki_build", WIKI / "build.py")
assert SPEC and SPEC.loader
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


def test_living_manuscript_contract_is_complete():
    report = MODULE.check()
    assert report["body_words"] >= 3500
    assert report["abstract_words"] >= 120
    assert report["citation_count"] >= 40
    assert report["bibliography_count"] >= 45


def test_split_retains_complete_paper_body():
    manifest = MODULE.load_manifest()
    text = (WIKI / manifest["canonical_page"]).read_text(encoding="utf-8")
    abstract, body = MODULE.split_manuscript(text)
    assert abstract.startswith("Magnetic-core models")
    assert body.startswith("# Introduction")
    assert "# Conclusion" in body


def test_unresolved_citation_is_rejected():
    assert MODULE.citation_keys("statement [@missing2026]") == {"missing2026"}
    available = MODULE.bibliography_keys(WIKI / "bibliography" / "references.bib")
    assert "missing2026" not in available


def test_snapshot_refuses_existing_output(tmp_path: Path):
    output = tmp_path / "already-exists"
    output.mkdir()
    with pytest.raises(MODULE.WikiError, match="already exists"):
        MODULE.snapshot(output, "journal", "journal-example-2026")


@pytest.mark.parametrize(
    ("kind", "name"),
    [
        ("conference", "conference-example-2026"),
        ("journal", "journal-example-2026.1"),
    ],
)
def test_document_release_identity_accepts_named_submission_types(kind: str, name: str):
    MODULE.validate_document_release(kind, name)


@pytest.mark.parametrize(
    ("kind", "name"),
    [
        ("draft", "draft-example-2026"),
        ("conference", "journal-example-2026"),
        ("journal", "current_state"),
    ],
)
def test_document_release_identity_rejects_ambiguous_names(kind: str, name: str):
    with pytest.raises(MODULE.WikiError):
        MODULE.validate_document_release(kind, name)


def test_document_release_output_must_be_staged_outside_repository(monkeypatch):
    monkeypatch.setattr(MODULE, "require_snapshot_tools", lambda: ("pandoc", "latexmk"))
    output = WIKI.parent / "paper" / "journal-example-2026"
    with pytest.raises(MODULE.WikiError, match="outside the repository"):
        MODULE.snapshot(output, "journal", "journal-example-2026")


def test_scientific_job_registry_covers_declared_artifacts():
    evidence = json.loads(
        (WIKI / "evidence" / "results.json").read_text(encoding="utf-8")
    )
    assert len(evidence["scientific_jobs"]) == 13
    assert sum(job["artifacts"] for job in evidence["scientific_jobs"]) == 222
    assert evidence["campaign"]["result_artifact_count"] == 222
    assert evidence["sources"]["acquisition_record_set"]["record_count"] == 30


def test_comparator_explanation_is_source_bound():
    page = (WIKI / "results" / "Scientific-Job-Results.md").read_text(
        encoding="utf-8"
    )
    assert "Why EIG did not beat the strong comparators" in page
    assert "Evidence-Sources.md#e4" in page
    assert "Evidence-Sources.md#e5" in page
    for source_id in range(1, 10):
        assert f'<a id="e{source_id}"></a>' in (
            WIKI / "evidence" / "Evidence-Sources.md"
        ).read_text(encoding="utf-8")


def test_new_reader_index_covers_public_pages_and_evidence_lookup():
    manifest = MODULE.load_manifest()
    index_path = WIKI / manifest["wiki"]["index"]
    index = index_path.read_text(encoding="utf-8")
    targets = {
        str((index_path.parent / target).resolve().relative_to(WIKI))
        for target in MODULE.local_markdown_targets(index)
        if (index_path.parent / target).resolve().suffix == ".md"
    }
    expected = set(MODULE.declared_public_pages(manifest)) - {
        manifest["wiki"]["index"],
        manifest["wiki"]["sidebar"],
    }
    assert expected <= targets
    assert "Verify a number" in index
    assert "E1--E9" in index


def test_acquisition_figure_is_bound_to_evidence_projection():
    evidence = WIKI / "evidence" / "results.json"
    manifest = json.loads(
        (WIKI / "assets" / "acquisition-diagnostics.json").read_text(
            encoding="utf-8"
        )
    )
    assert manifest["evidence_projection_sha256"] == MODULE.sha256(evidence)
    assert manifest["figure_sha256"] == MODULE.sha256(
        WIKI / "assets" / manifest["figure"]
    )
    assert manifest["evidence_sources"] == ["E4", "E5"]


@pytest.mark.parametrize(
    "text",
    [
        "token gh" + "p_ABCDEFGHIJKLMNOPQRSTUVWXYZ123456",
        "generated by "
        + "".join(chr(value) for value in (67, 104, 97, 116, 71, 80, 84)),
        "/" + "users/example/private/project",
        "Current Presen" + "tation note",
        "The current manuscript preser" + "ves the old layout",
        "a one-way mir" + "ror of the source",
        "This wiki is the liv" + "ing manuscript",
    ],
)
def test_public_disclosure_patterns_are_detected(text: str):
    assert any(pattern.search(text) for pattern in MODULE.BANNED_PUBLIC_PATTERNS.values())


def test_repository_landing_page_is_evidence_led():
    readme = (WIKI.parent / "README.md").read_text(encoding="utf-8")
    assert readme == MODULE.render_repository_readme()
    assert "## Current result" in readme
    assert "wiki/evidence/Evidence-Sources.md#e4" in readme
    assert "wiki/evidence/Evidence-Sources.md#e5" in readme
    assert "wiki/evidence/Evidence-Sources.md#e7" in readme
    assert "wiki/evidence/Evidence-Sources.md#e9" in readme
    assert "20260817T072230Z_401e3030fe13" in readme
    assert MODULE.sha256(WIKI.parent / "README.md") == MODULE.check()[
        "repository_readme_sha256"
    ]


def test_public_wiki_projection_is_flat_and_rewrites_links():
    manifest = MODULE.load_manifest()
    pages = MODULE.declared_public_pages(manifest)
    assert len({Path(page).name for page in pages}) == len(pages)
    rendered = MODULE.render_public_wiki_page(
        "Home.md", manifest, "1" * 40
    )
    assert not rendered.startswith("---")
    assert "](Evidence-Sources.md#e4)" in rendered
    assert "](Project-Status.md)" in rendered
    assert "wiki/evidence/Evidence-Sources.md" not in rendered


def test_public_wiki_staging_refuses_existing_output(tmp_path: Path):
    output = tmp_path / "existing"
    output.mkdir()
    with pytest.raises(MODULE.WikiError, match="already exists"):
        MODULE.stage_public_wiki(output)


def test_staged_wiki_validation_rejects_broken_anchor(tmp_path: Path):
    (tmp_path / "Home.md").write_text(
        "# Home\n\n[Missing](Results.md#missing)\n", encoding="utf-8"
    )
    (tmp_path / "Results.md").write_text("# Results\n", encoding="utf-8")
    with pytest.raises(MODULE.WikiError, match="broken staged Wiki anchor"):
        MODULE.validate_public_wiki_tree(tmp_path)


def test_only_full_manuscript_is_a_paper_source():
    manifest = MODULE.load_manifest()
    paper_sources = []
    for page in MODULE.declared_public_pages(manifest):
        text = (WIKI / page).read_text(encoding="utf-8")
        if re.search(r"(?m)^paper_source:\s*true\s*$", text):
            paper_sources.append(page)
    assert paper_sources == [manifest["canonical_page"]]


def test_ci_validates_wiki_without_rendering_a_document_snapshot():
    workflow = (WIKI.parent / ".github" / "workflows" / "ci.yml").read_text(
        encoding="utf-8"
    )
    assert "python wiki/build.py check" in workflow
    assert "python wiki/build.py stage-wiki" in workflow
    assert "pytest -q wiki/tests" in workflow
    assert "latexmk" not in workflow
    assert "paper/current_state/source" not in workflow
    assert "20260812T035654Z_a0703698ace9" not in workflow
    assert "paper/current_state/results.lock.yaml" in workflow


def test_compatibility_docs_delegate_claims_and_protocol_to_wiki():
    for relative in ("docs/CLAIMS_EVIDENCE.md", "docs/EXPERIMENT_PROTOCOL.md"):
        text = (WIKI.parent / relative).read_text(encoding="utf-8")
        assert "../wiki/" in text
        assert not re.search(r"20\d{6}T\d{6}Z_[0-9a-f]{12}", text)
