#!/usr/bin/env bash
# Shared fail-closed runtime for every Magnetic Core SLURM job.

set -Eeuo pipefail
umask 027

BOOTSTRAP_CODE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"

require_slurm() {
    if [[ -z "${SLURM_JOB_ID:-}" || -z "${SLURM_JOB_NODELIST:-}" ]]; then
        echo "FATAL: scientific pipeline stages must run inside a SLURM allocation" >&2
        exit 70
    fi
}

load_run() {
    require_slurm
    if [[ $# -ne 1 ]]; then
        echo "usage: load_run RUN_DIR" >&2
        exit 64
    fi

    MAGCORE_RUN_DIR="$(cd "$1" && pwd -P)"
    [[ -f "$MAGCORE_RUN_DIR/provenance/run.env" ]] || {
        echo "FATAL: missing run provenance: $MAGCORE_RUN_DIR/provenance/run.env" >&2
        exit 66
    }

    # run.env is generated by submit.sh using shell-escaped values.
    # shellcheck disable=SC1090
    source "$MAGCORE_RUN_DIR/provenance/run.env"
    local required
    for required in MAGCORE_RUN_ID MAGCORE_PROJECT_ROOT MAGCORE_CODE_ROOT MAGCORE_DATA_ROOT \
        MAGCORE_GIT_REVISION MAGCORE_SOURCE_STATUS_SHA256 MAGCORE_SOURCE_ARCHIVE_SHA256 \
        MAGCORE_CONFIG_SHA256 MAGCORE_DATA_MANIFEST_SHA256 \
        MAGCORE_DEPENDENCY_LOCK_SHA256 MAGCORE_CONFIG_MODE MAGCORE_SUBMIT_PARTITION \
        MAGCORE_VENV; do
        [[ -n "${!required:-}" ]] || {
            echo "FATAL: missing required run provenance variable: $required" >&2
            exit 66
        }
    done
    [[ "$MAGCORE_GIT_REVISION" =~ ^[0-9a-f]{40}$ ]] || {
        echo "FATAL: malformed run git revision" >&2; exit 66;
    }
    for required in MAGCORE_SOURCE_STATUS_SHA256 MAGCORE_SOURCE_ARCHIVE_SHA256 \
        MAGCORE_CONFIG_SHA256 MAGCORE_DATA_MANIFEST_SHA256 MAGCORE_DEPENDENCY_LOCK_SHA256; do
        [[ "${!required}" =~ ^[0-9a-f]{64}$ ]] || {
            echo "FATAL: malformed run provenance digest: $required" >&2
            exit 66
        }
    done
    PROJECT_ROOT="$(cd "$MAGCORE_PROJECT_ROOT" && pwd -P)"
    MAGCORE_CODE_ROOT="$(cd "$MAGCORE_CODE_ROOT" && pwd -P)"
    case "$MAGCORE_RUN_DIR/" in
        "$PROJECT_ROOT/runs/"*) ;;
        *) echo "FATAL: run directory is outside $PROJECT_ROOT/runs" >&2; exit 65 ;;
    esac
    [[ "$MAGCORE_CODE_ROOT" == "$MAGCORE_RUN_DIR/source" && -f "$MAGCORE_CODE_ROOT/slurm/common.sh" ]] || {
        echo "FATAL: immutable source snapshot is missing or mismatched" >&2
        exit 66
    }
    export MAGCORE_RUN_DIR PROJECT_ROOT
    export MAGCORE_CODE_ROOT MAGCORE_DATA_ROOT
    export MAGCORE_RUN_ID MAGCORE_PROJECT_ROOT MAGCORE_GIT_REVISION
    export MAGCORE_SOURCE_STATUS_SHA256 MAGCORE_SOURCE_ARCHIVE_SHA256
    export MAGCORE_CONFIG_SHA256 MAGCORE_DATA_MANIFEST_SHA256
    export MAGCORE_DEPENDENCY_LOCK_SHA256 MAGCORE_CONFIG_MODE MAGCORE_RETRY_OF
    export MAGCORE_SUBMIT_PARTITION MAGCORE_VENV

    export PYTHONHASHSEED="${PYTHONHASHSEED:-0}"
    export MPLBACKEND=Agg
    export MPLCONFIGDIR="$MAGCORE_RUN_DIR/tmp/matplotlib/${SLURM_JOB_ID}_${SLURM_ARRAY_TASK_ID:-0}"
    export OMP_NUM_THREADS=1
    export MKL_NUM_THREADS=1
    export OPENBLAS_NUM_THREADS=1
    export NUMEXPR_NUM_THREADS=1
    export VECLIB_MAXIMUM_THREADS=1
    export PYTHONNOUSERSITE=1
    export PYTHONDONTWRITEBYTECODE=1
    mkdir -p "$MPLCONFIGDIR"

    module load python/3.12
    if [[ -n "${MAGCORE_VENV:-}" ]]; then
        # shellcheck disable=SC1091
        source "$MAGCORE_VENV/bin/activate"
    fi
    export PYTHONPATH="$MAGCORE_CODE_ROOT/src${PYTHONPATH:+:$PYTHONPATH}"
    cd "$MAGCORE_CODE_ROOT"
}

init_task() {
    STAGE="$1"
    TASK_ID="$2"
    TASK_KEY="${STAGE}_${TASK_ID}"
    STATUS_DIR="$MAGCORE_RUN_DIR/status"
    RESULT_DIR="$MAGCORE_RUN_DIR/results/$STAGE/$TASK_ID"
    PROVENANCE_DIR="$MAGCORE_RUN_DIR/provenance/jobs"
    mkdir -p "$STATUS_DIR" "$RESULT_DIR" "$PROVENANCE_DIR"
    rm -f "$STATUS_DIR/$TASK_KEY.done" "$STATUS_DIR/$TASK_KEY.failed"
    STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    export STAGE TASK_ID TASK_KEY STATUS_DIR RESULT_DIR PROVENANCE_DIR STARTED_AT
    trap 'task_failed "$?" "$LINENO"' ERR INT TERM

    printf '{"stage":"%s","task":"%s","job_id":"%s","array_job_id":"%s","array_task_id":"%s","node_list":"%s","partition":"%s","seed_or_task":"%s","git_revision":"%s","configuration_sha256":"%s","data_manifest_sha256":"%s","dependency_lock_sha256":"%s","started_at":"%s"}\n' \
        "$STAGE" "$TASK_ID" "$SLURM_JOB_ID" "${SLURM_ARRAY_JOB_ID:-}" \
        "${SLURM_ARRAY_TASK_ID:-}" "$SLURM_JOB_NODELIST" "${SLURM_JOB_PARTITION:-}" \
        "$TASK_ID" "${MAGCORE_GIT_REVISION:-}" "${MAGCORE_CONFIG_SHA256:-}" \
        "${MAGCORE_DATA_MANIFEST_SHA256:-}" "${MAGCORE_DEPENDENCY_LOCK_SHA256:-}" \
        "$STARTED_AT" > "$PROVENANCE_DIR/$TASK_KEY.json.partial"
}

task_failed() {
    local code="$1" line="$2"
    trap - ERR INT TERM
    local ended_at
    ended_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '{"stage":"%s","task":"%s","job_id":"%s","exit_code":%s,"line":%s,"ended_at":"%s"}\n' \
        "${STAGE:-unknown}" "${TASK_ID:-unknown}" "$SLURM_JOB_ID" "$code" "$line" "$ended_at" \
        > "${STATUS_DIR:-$MAGCORE_RUN_DIR/status}/${TASK_KEY:-unknown}.failed"
    exit "$code"
}

task_done() {
    local ended_at
    ended_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '{"stage":"%s","task":"%s","job_id":"%s","exit_code":0,"ended_at":"%s"}\n' \
        "$STAGE" "$TASK_ID" "$SLURM_JOB_ID" "$ended_at" > "$STATUS_DIR/$TASK_KEY.done.partial"
    mv "$STATUS_DIR/$TASK_KEY.done.partial" "$STATUS_DIR/$TASK_KEY.done"
    python - <<'PY' > "$PROVENANCE_DIR/$TASK_KEY.environment.txt.partial"
import os, platform, sys
for key in sorted(k for k in os.environ if k.startswith("SLURM_")):
    print(f"{key}={os.environ[key]}")
print(f"python={sys.version}")
print(f"platform={platform.platform()}")
PY
    mv "$PROVENANCE_DIR/$TASK_KEY.environment.txt.partial" "$PROVENANCE_DIR/$TASK_KEY.environment.txt"
    mv "$PROVENANCE_DIR/$TASK_KEY.json.partial" "$PROVENANCE_DIR/$TASK_KEY.json"
    trap - ERR INT TERM
}

run_python() {
    srun --ntasks=1 --cpus-per-task="${SLURM_CPUS_PER_TASK:-1}" --cpu-bind=cores \
        env MAGCORE_RUN_DIR="$MAGCORE_RUN_DIR" PROJECT_ROOT="$PROJECT_ROOT" \
        MAGCORE_PROJECT_ROOT="$MAGCORE_PROJECT_ROOT" MAGCORE_CODE_ROOT="$MAGCORE_CODE_ROOT" \
        MAGCORE_DATA_ROOT="$MAGCORE_DATA_ROOT" MAGCORE_RUN_ID="$MAGCORE_RUN_ID" \
        MAGCORE_GIT_REVISION="$MAGCORE_GIT_REVISION" \
        MAGCORE_SOURCE_STATUS_SHA256="$MAGCORE_SOURCE_STATUS_SHA256" \
        MAGCORE_SOURCE_ARCHIVE_SHA256="$MAGCORE_SOURCE_ARCHIVE_SHA256" \
        MAGCORE_CONFIG_SHA256="$MAGCORE_CONFIG_SHA256" \
        MAGCORE_DATA_MANIFEST_SHA256="$MAGCORE_DATA_MANIFEST_SHA256" \
        MAGCORE_DEPENDENCY_LOCK_SHA256="$MAGCORE_DEPENDENCY_LOCK_SHA256" \
        MAGCORE_CONFIG_MODE="$MAGCORE_CONFIG_MODE" \
        MAGCORE_SUBMIT_PARTITION="$MAGCORE_SUBMIT_PARTITION" MAGCORE_VENV="$MAGCORE_VENV" \
        PYTHONPATH="$PYTHONPATH" \
        PYTHONNOUSERSITE=1 PYTHONDONTWRITEBYTECODE=1 MPLBACKEND=Agg \
        MPLCONFIGDIR="$MPLCONFIGDIR" python "$@"
}

run_experiment() {
    local stage="$1" fallback="$2"
    shift 2
    [[ -f "$MAGCORE_CODE_ROOT/experiments/$fallback" ]] || {
        echo "FATAL: standalone Magnetic experiment is missing: experiments/$fallback" >&2
        exit 69
    }
    run_python "$MAGCORE_CODE_ROOT/experiments/$fallback" "$@"
}

validate_json() {
    local path="$1"
    [[ -s "$path" ]]
    python - "$path" <<'PY'
import json, math, pathlib, sys
p = pathlib.Path(sys.argv[1])
obj = json.loads(p.read_text())
def check(x):
    if isinstance(x, float) and not math.isfinite(x):
        raise ValueError(f"non-finite value in {p}")
    if isinstance(x, dict):
        for value in x.values(): check(value)
    elif isinstance(x, list):
        for value in x: check(value)
check(obj)
PY
}
